version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    expose:
      - "80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/build:/app/static
    expose:
      - "80"
    depends_on:
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - frontend
      - backend
